sudo: false
language: python


env:
    matrix:
        - DJANGO=Django==1.8.8
        - DJANGO=Django==1.9.1

python:
    - '2.7'
    - '3.4'
    - '3.5'

before_install:
    - pip install codecov

install:
    - pip install --pre $DJANGO
    - pip install -e .[test]

script:
    - py.test --cov=django_healthchecks --cov-report=term-missing

after_success: 
    - codecov
